In [2]:
import numpy as np
# create array using numpy
# Create a ID array
arr1 = np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [5]:
arr2 = np.array([1,2,3,4,5])
arr2 = arr2.reshape(1,5)
print(arr2)

[[1 2 3 4 5]]


In [6]:
arr2 = np.array([[1,2,3,4,5]])
arr2.shape

(1, 5)

In [7]:
arr3 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr3)
print(arr3.shape)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
(2, 5)


In [11]:
np.arange(0, 6,2).reshape(3,1)

array([[0],
       [2],
       [4]])

In [13]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [15]:
# identity matrix
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [ ]:
# Attribute of Array

arr = np.array([[1,2,3],[4,5,6]])

print("Array \n:", arr)
print("Array shape:", arr.shape)
print("Array dimension:", arr.ndim)
print("Array size:", arr.size)
print("Array data type:", arr.dtype)
print("Array item size:", arr.itemsize)

Array 
: [[1 2 3]
 [4 5 6]]
Array shape: (2, 3)
Array dimension: 2
Array size: 6
Array data type: int64
Array item size: 8


In [26]:
## Vectorization in Numpy
arr1=(np.array([1,2,3,4,5]))
arr2=(np.array([6,7,8,9,10]))

## Element wise addition

print("Addition:",arr1+arr2)

## Element wise substraction
print("Substraction:", arr1-arr2)
## Element wise Multiplication
print("Multiplication",arr1*arr2)
## Element wise division
print("Division",arr1/arr2)

Addition: [ 7  9 11 13 15]
Substraction: [-5 -5 -5 -5 -5]
Multiplication [ 6 14 24 36 50]
Division [0.16666667 0.28571429 0.375      0.44444444 0.5       ]


In [4]:
## Univarsal function
arr = np.array([2,3,4,5,6])

## square root 

print(np.sqrt(arr))

# Exponatial
print(np.exp(arr))
# sine
print(np.sin(arr))
# natural log
print(np.log(arr))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [3]:
# Array slicing and Indexing
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("Array:\n",arr)

Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [3]:
print(np.arange(1,20))

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [4]:
print(np.arange(2,20,2))

[ 2  4  6  8 10 12 14 16 18]


In [15]:
a3 =(np.array([1,2,3,4,5,6]))
a4 =(np.array([6,7,8,9,10,11]))

print("sum:",a3+a4)

sum: [ 7  9 11 13 15 17]


In [16]:
print("Max:",max(a3))
print("Min:",min(a3))

Max: 6
Min: 1


In [ ]:
arr1 = np.arange(0,20)
print(arr.reshape(4,5))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [43]:
arr1[0]
arr1[1]
arr1[2]

np.int64(3)

In [3]:
arr2 =np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr2.reshape(2,5))
arr2[1][1]
arr2[0:,2:]

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


array([[ 3,  4,  5],
       [ 8,  9, 10]])

In [8]:
print(arr[0][0])
print(arr[0:1,2])

1
[3]


In [5]:
arr[2,2]=100
print(arr)

[[  1   2   3   4]
 [  5   6   7   8]
 [  9  10 100  12]]


In [6]:
arr[1:]=100
print(arr)

[[  1   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


In [10]:
### statisical conceopt --Normalization
## to have a mean of 0 standard  deviation of 1
data = np.array([1,2,3,4,5])

# calculate the mean and standard deviation

mean= np.mean(data)
std_dev = np.std(data)

# Normalized the data 
normalized_data =(data - mean)/std_dev
print("Normalized data:",normalized_data)

Normalized data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [11]:
# Variance

variance = np.var(data)
print("Variance:",variance)

Variance: 2.0


In [14]:
# Logical
data= np.array([1,2,3,4,5,6,7,8,9,10]) 
data[(data>=5) & (data<=8)]

array([5, 6, 7, 8])