In [2]:
import numpy as np
# create array using numpy
# Create a ID array
arr1 = np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [5]:
arr2 = np.array([1,2,3,4,5])
arr2 = arr2.reshape(1,5)
print(arr2)

[[1 2 3 4 5]]


In [6]:
arr2 = np.array([[1,2,3,4,5]])
arr2.shape

(1, 5)

In [7]:
arr3 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr3)
print(arr3.shape)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
(2, 5)


In [11]:
np.arange(0, 6,2).reshape(3,1)

array([[0],
       [2],
       [4]])

In [13]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [15]:
# identity matrix
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [ ]:
# Attribute of Array

arr = np.array([[1,2,3],[4,5,6]])

print("Array \n:", arr)
print("Array shape:", arr.shape)
print("Array dimension:", arr.ndim)
print("Array size:", arr.size)
print("Array data type:", arr.dtype)
print("Array item size:", arr.itemsize)

Array 
: [[1 2 3]
 [4 5 6]]
Array shape: (2, 3)
Array dimension: 2
Array size: 6
Array data type: int64
Array item size: 8


In [26]:
## Vectorization in Numpy
arr1=(np.array([1,2,3,4,5]))
arr2=(np.array([6,7,8,9,10]))

## Element wise addition

print("Addition:",arr1+arr2)

## Element wise substraction
print("Substraction:", arr1-arr2)
## Element wise Multiplication
print("Multiplication",arr1*arr2)
## Element wise division
print("Division",arr1/arr2)

Addition: [ 7  9 11 13 15]
Substraction: [-5 -5 -5 -5 -5]
Multiplication [ 6 14 24 36 50]
Division [0.16666667 0.28571429 0.375      0.44444444 0.5       ]


In [27]:
## Univarsal function
arr = np.array([2,3,4,5,6])

## square root 

print(np.sqrt(arr))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
